# Generated by Django 3.2.8 on 2022-02-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='photo',
            field=models.ImageField(default='', upload_to='img/%y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='tot_pri',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='tot_qty',
            field=models.IntegerField(default=1),
        ),
    ]
