# Generated by Django 3.2.8 on 2022-03-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0002_auto_20220226_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignitem_info',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='in_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='ind_pri',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='tot_pri',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='tot_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='maintainitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='removeitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='replaceitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
