# Generated by Django 3.2.8 on 2022-03-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_faculty_joiningdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Furniture', '0003_auto_20220302_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignitem_info',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignitem_info',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Resources.faculty'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='removeitem',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replaceitem',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
    ]
