# Generated by Django 3.2.8 on 2022-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0006_alter_assignitem_info_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignitem_info',
            name='assigned_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maintainitem',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='removeitem',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='replaceitem',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
    ]
