# Generated by Django 3.2.8 on 2022-02-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_info',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('qty', models.IntegerField(default=1)),
                ('Pur_from', models.CharField(max_length=50)),
                ('order_ref', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('in_no', models.IntegerField()),
                ('spec', models.CharField(max_length=50)),
                ('warn', models.DateField()),
                ('ind_pri', models.IntegerField()),
                ('auth', models.CharField(max_length=50)),
            ],
        ),
    ]
