# Generated by Django 3.2.8 on 2022-02-05 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_faculty_joiningdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0002_alter_item_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_item_info',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hardware.item_info')),
                ('quantity', models.IntegerField(default=1)),
                ('lab_name', models.CharField(max_length=50, null='True')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(null='True', on_delete=django.db.models.deletion.DO_NOTHING, to='Resources.faculty')),
            ],
        ),
    ]
