# Generated by Django 3.2.8 on 2022-02-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_assign_item_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='assign_date',
            field=models.DateField(),
        ),
    ]
