# Generated by Django 3.2.8 on 2022-02-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_alter_assign_item_info_assign_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_item_info',
            old_name='id',
            new_name='item_id',
        ),
    ]
