# Generated by Django 3.2.8 on 2022-02-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_rename_id_assign_item_info_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_item_info',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assign_item_info',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.item_info', unique=True),
        ),
    ]
