# Generated by Django 3.2.8 on 2022-02-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_alter_assign_item_info_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_info',
            old_name='id',
            new_name='item_id',
        ),
    ]
