# Generated by Django 3.2.8 on 2022-02-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_rename_id_item_info_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='item_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.item_info'),
        ),
    ]
