# Generated by Django 3.2.8 on 2022-02-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_alter_item_info_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
