# Generated by Django 3.2.8 on 2022-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_alter_assign_item_info_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='assigned_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='assign_item_info',
            name='faculty',
            field=models.CharField(default='', max_length=50),
        ),
    ]
