# Generated by Django 3.2.8 on 2022-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_auto_20220207_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='item_id',
            field=models.IntegerField(default=1),
        ),
    ]
