# Generated by Django 3.2.8 on 2022-02-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0014_alter_assign_item_info_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.item_info'),
        ),
    ]
