# Generated by Django 3.2.8 on 2022-02-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0015_alter_assign_item_info_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='item_id',
            field=models.IntegerField(default=1),
        ),
    ]
