# Generated by Django 3.2.8 on 2022-02-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0016_alter_assign_item_info_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hardware.item_info'),
        ),
    ]
