# Generated by Django 3.2.8 on 2022-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0019_alter_assign_item_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
