# Generated by Django 3.2.8 on 2022-02-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0022_maintain_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replace_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.item_info')),
            ],
        ),
    ]
