# Generated by Django 3.2.8 on 2022-02-13 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0024_remove_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='replace_item',
            name='added_by',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
    ]
