# Generated by Django 3.2.8 on 2022-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0027_rename_date_maintain_item_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_info',
            name='photo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_info',
            name='tot_pri',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
