# Generated by Django 3.2.8 on 2022-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0028_auto_20220223_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='photo',
            field=models.ImageField(upload_to='image/jpg'),
        ),
    ]
