# Generated by Django 3.2.8 on 2022-02-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0030_alter_item_info_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_info',
            name='tot_qty',
            field=models.IntegerField(default=1),
        ),
    ]
