# Generated by Django 3.2.8 on 2022-03-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0031_item_info_tot_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='in_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='ind_pri',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='tot_pri',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='tot_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='maintain_item',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='remove_item',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='replace_item',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
