# Generated by Django 3.2.8 on 2022-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0035_alter_assign_item_info_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_item_info',
            name='assigned_by',
            field=models.CharField(max_length=50),
        ),
    ]
