# Generated by Django 3.2.8 on 2022-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0036_alter_assign_item_info_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain_item',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='remove_item',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='replace_item',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
    ]
