# Generated by Django 3.2.8 on 2021-12-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thesis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thesis',
        ),
    ]
