# Generated by Django 3.1.3 on 2020-12-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('department_course_rights', 'Manage Department and Courses'), ('faculty_rights', 'Manage Faculties'), ('student_rights', 'Manage Students'), ('marks_rights', 'Manage Marks'), ('marks_view_rights', 'View Marks'), ('attendance_rights', 'Manage Attendance'), ('attendance_view_rights', 'View Attendance'), ('email_rights', 'Send Emails'), ('sms_rights', 'Send SMS'), ('api_rights', 'Add Send Grid and Twilio API Key'), ('permission_rights', 'Grant Permissions')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Type', models.IntegerField()),
                ('UserCollegeID', models.CharField(max_length=64, unique=True)),
                ('Verified', models.BooleanField(default=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First', models.CharField(max_length=150)),
                ('Last', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Post', models.CharField(max_length=256)),
                ('Qualification', models.CharField(max_length=1024)),
                ('FacultyCollegeID', models.CharField(max_length=64, unique=True)),
                ('Contact', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=1024)),
                ('Photo', models.TextField()),
                ('DOB', models.DateField()),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128)),
                ('Branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.branch')),
            ],
        ),
        migrations.CreateModel(
            name='SendGridAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=512)),
                ('Token', models.CharField(max_length=512)),
                ('Notify', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
                ('Theory_Lectures', models.IntegerField()),
                ('Lab_Lectures', models.IntegerField()),
                ('Semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First', models.CharField(max_length=150)),
                ('Last', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Enrollment', models.CharField(max_length=64, unique=True)),
                ('Contact', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('Category', models.CharField(max_length=7)),
                ('Address', models.CharField(max_length=1024)),
                ('Photo', models.TextField()),
                ('Branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Resources.branch')),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Resources.course')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Resources.department')),
                ('Semester_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Resources.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MidTerm1', models.IntegerField()),
                ('MidTerm2', models.IntegerField()),
                ('Viva1', models.IntegerField()),
                ('Viva2', models.IntegerField()),
                ('Viva3', models.IntegerField()),
                ('Quiz1', models.IntegerField()),
                ('Timestamp', models.DateTimeField()),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.student')),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.faculty')),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.subject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.department'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.course'),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Theory_Lectures', models.BooleanField(default=False)),
                ('Lab_Lectures', models.BooleanField(default=False)),
                ('Timestamp', models.DateTimeField()),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.student')),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.subject')),
            ],
        ),
    ]
