# Generated by Django 3.1.3 on 2020-12-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_auto_20201207_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='Viva3',
            new_name='MidTerm1Total',
        ),
        migrations.AddField(
            model_name='marks',
            name='MidTerm2Total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='Quiz1Total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='Quiz2',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='Quiz2Total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='Viva1Total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='Viva2Total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marks',
            name='Subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Resources.subject'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
