# Generated by Django 3.1.3 on 2020-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_auto_20201209_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='MidTerm1Total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='MidTerm2Total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Quiz1Total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Quiz2Total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Viva1Total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Viva2Total',
            field=models.IntegerField(default=10),
        ),
    ]
