# Generated by Django 3.2.8 on 2021-11-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=50)),
                ('Users', models.IntegerField()),
                ('PurD', models.DateField()),
                ('ValD', models.DateField()),
                ('ExpD', models.DateField()),
                ('Keys', models.IntegerField()),
                ('PurForSub', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
            ],
        ),
    ]
