# Generated by Django 3.2.8 on 2021-11-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software_info',
            name='LName',
        ),
    ]
