# Generated by Django 3.2.8 on 2021-11-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0002_remove_software_info_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(max_length=50)),
                ('LabI', models.CharField(max_length=200)),
            ],
        ),
    ]
