# Generated by Django 3.2.8 on 2022-02-17 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0004_auto_20220217_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='software_info',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 17)),
            preserve_default=False,
        ),
    ]
