# Generated by Django 3.2.8 on 2022-02-18 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Software', '0005_software_info_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software_manage',
            name='Keys',
        ),
        migrations.AlterField(
            model_name='software_manage',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
