# Generated by Django 3.2.8 on 2022-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0006_auto_20220218_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software_info',
            name='Keys',
        ),
        migrations.RemoveField(
            model_name='software_info',
            name='date',
        ),
        migrations.AddField(
            model_name='software_manage',
            name='Users',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
