# Generated by Django 3.2.8 on 2022-03-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Software', '0008_software_info_tot_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_info',
            name='Tot_users',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='software_info',
            name='Users',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='software_info',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='software_info',
            name='ind_pri',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='software_manage',
            name='Users',
            field=models.PositiveIntegerField(),
        ),
    ]
