# Generated by Django 3.2.8 on 2022-03-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0009_auto_20220302_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_info',
            name='auth',
            field=models.CharField(max_length=50),
        ),
    ]
