# Generated by Django 3.2.8 on 2022-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0010_alter_software_info_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_manage',
            name='assigned_by',
            field=models.CharField(max_length=50),
        ),
    ]
